train <- copy(trainData)
test<-copy(testData)
holdout <- copy(holdoutData)

table(train$addrUsedNum)
table(train$age)
table(train$applicantContact)
table(train$avgMonthCall)
table(train$browserUsedNum)
table(train$callBlacklist)
table(train$callEcpNum)
table(train$callLaws)
table(train$called5)
table(train$cellphoneAuth)
table(train$childrenNum)
table(train$consumeFreg)
table(train$consumeLineRate)
table(train$consumeTop)
table(train$creditCashAvg)
table(train$creditCashFreq)
table(train$creditWD3Months)
table(train$creditWDAvg)
table(train$creditWDFreq)
table(train$currentJobyear)
table(train$ecpNum)
table(train$goOut120)
table(train$hasShCISReport)
table(train$highZhimaScore)
table(train$ipUsedNum)
table(train$lastMonthOverdrawNum)
table(train$loanPurpose)
table(train$loansCalls1)
table(train$loansCalls3)
table(train$localFriends)
table(train$longTimeShutdown)
table(train$marry)
table(train$mealsNum)
table(train$month62ConsumeAvg)
table(train$monthIncome)
table(train$networkTime6)
table(train$nightConsumeNum)
table(train$noNeedMobileAuthCheck)
table(train$normalContact)
table(train$post12PMFeeAmount)
table(train$post12PMFeeNum)
table(train$post6MonthOverdrawNum)
table(train$postMonthConsumeFreg)
table(train$sex)
table(train$shCISCreditLine)
table(train$shCISLoanQueryNo_3month)
table(train$tachEcp)
table(train$thisCityIsTop3)
table(train$transFalsePast6)
table(train$transFalsePastMonth)
table(train$trustAddr)
table(train$unionpayAnswer)
table(train$unionpayPosConsumeCityRank)
table(train$useCardAmountAvg)
table(train$useCardLastTime)
table(train$useCardNumPost6)
table(train$useCardPM)
table(train$useCardSumRank)
table(train$workCondition)
table(train$zhiceCar)
table(train$zhiceHouse)
table(train$zhimaScore)
table(train$tenor)
table(train$flgDPD)
table(train$final_score)



print(woeCalc(train, "addrUsedNum", "flgDPD", binning=c(-Inf, 0, Inf)))
print(woeCalc(train, "age", "flgDPD", binning=c(-Inf, 29, 36, Inf)))
# print(woeCalc(train, "amuseConsumeFreq", "flgDPD", binning=c(-Inf, 0, Inf)))
print(woeCalc(train, "applicantContact", "flgDPD", binning=c(-Inf, 0, Inf)))
print(woeCalc(train, "avgMonthCall", "flgDPD", binning=c(-Inf, 135, 180, 244, 359, Inf)))
print(woeCalc(train, "browserUsedNum", "flgDPD", binning=c(-Inf, 0, Inf)))
# print(woeCalc(train, "callBlacklist", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "callEcpNum", "flgDPD", binning=c(-Inf, 15, 35, 240, Inf)))
print(woeCalc(train, "callLaws", "flgDPD", binning=c(-Inf, 0, Inf)))
print(woeCalc(train, "called5", "flgDPD", binning=c(-Inf, 5, 6, Inf)))
print(woeCalc(train, "cardTerm", "flgDPD", binning=c(-Inf, 12, Inf)))
print(woeCalc(train, "cardType", "flgDPD", binning=c(-Inf, 0, Inf)))
# print(woeCalc(train, "cellphoneAuth", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "childrenNum", "flgDPD", binning=c(-Inf, 0, 1 , Inf)))
print(woeCalc(train, "consumeFreg", "flgDPD", binning=c(-Inf, 2, 4, Inf)))
print(woeCalc(train, "consumeLineRate", "flgDPD", binning=10))
print(woeCalc(train, "consumeTop", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "creditCashAvg", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "creditCashFreq", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "creditWD3Months", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "creditWDAvg", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "creditWDFreq", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "currentJobyear", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "ecpNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "goOut120", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "hasShCISReport", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "highZhimaScore", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "ipUsedNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "lastMonthOverdrawNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "loanPurpose", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "loansCalls1", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "loansCalls3", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "localFriends", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "longTimeShutdown", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "marry", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "mealsNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "month62ConsumeAvg", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "monthIncome", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "networkTime6", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "nightConsumeNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "noNeedMobileAuthCheck", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "normalContact", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "post12PMFeeAmount", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "post12PMFeeNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "post6MonthOverdrawNum", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "postMonthConsumeFreg", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "sex", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "shCISCreditLine", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "shCISLoanQueryNo_3month", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "tachEcp", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "thisCityIsTop3", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "transFalsePast6", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "transFalsePastMonth", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "trustAddr", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "unionpayAnswer", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "unionpayPosConsumeCityRank", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "useCardAmountAvg", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "useCardLastTime", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "useCardNumPost6", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "useCardPM", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "useCardSumRank", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "workCondition", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "zhiceCar", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "zhiceHouse", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "zhimaScore", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "tenor", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "flgDPD", "flgDPD", binning=c(-Inf, , Inf)))
print(woeCalc(train, "final_score", "flgDPD", binning=c(-Inf, , Inf)))
